# Generated by Django 4.0.5 on 2022-06-14 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('news_title', models.CharField(max_length=200)),
                ('featured_image', models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='news/')),
            ],
        ),
    ]
